### ISSUE TITLE
Fix or docs for compile time log flags

### ISSUE THREAD

**Issue by D4nte** [status-im/nwaku#473] opened 2021-04-09 01:06 UTC
EDIT: This is for compiler flag, see comments below

----

When trying to use the `--log-level` argument to set the log level, it has no effect, e.g.:

Debug logs show when log level is set to `info`.
```
▶ ./build/wakunode2 --log-level=info
DBG 2021-04-09 11:03:35.776+10:00 UPnP                                       topics="nat" tid=930894 file=nat.nim:67 msg="Internet Gateway Device not found. Giving up."
DBG 2021-04-09 11:03:35.787+10:00 NAT-PMP                                    topics="nat" tid=930894 file=nat.nim:91 msg="the gateway does not support nat-pmp"
INF 2021-04-09 11:03:35.791+10:00 Initializing networking                    topics="wakunode" tid=930894 file=wakunode2.nim:127 hostAddress=/ip4/0.0.0.0/tcp/60000 announcedAddresses=@[]
```

No trace logs are show hen log level is set to `trace`

```
▶ ./build/wakunode2 --log-level=trace
DBG 2021-04-09 11:05:26.001+10:00 UPnP                                       topics="nat" tid=931087 file=nat.nim:67 msg="Internet Gateway Device not found. Giving up."
DBG 2021-04-09 11:05:26.012+10:00 NAT-PMP                                    topics="nat" tid=931087 file=nat.nim:91 msg="the gateway does not support nat-pmp"
INF 2021-04-09 11:05:26.016+10:00 Initializing networking                    topics="wakunode" tid=931087 file=wakunode2.nim:127 hostAddress=/ip4/0.0.0.0/tcp/60000 announcedAddresses=@[]
DBG 2021-04-09 11:05:26.016+10:00 About to accept incoming connection        topics="libp2p switch" tid=931087 file=switch.nim:318
DBG 2021-04-09 11:05:26.016+10:00 Started libp2p node                        topics="libp2p switch" tid=931087 file=switch.nim:368 peer="(peerId: \"16Uiu2HAmMqF1RsxqHfbYsJ2Mk8UXWiVHVG9LA57beLhNWznFqhVm\", addrs: @[\"/ip4/0.0.0.0/tcp/60000\"], protocols: @[\"/ipfs/id/1.0.0\"], protoVersion: \"\", agentVersion: \"\")"
INF 2021-04-09 11:05:26.016+10:00 PeerInfo                                   topics="wakunode" tid=931087 file=wakunode2.nim:161 peerId=16U*nFqhVm addrs=@[/ip4/0.0.0.0/tcp/60000]
INF 2021-04-09 11:05:26.016+10:00 Listening on                               topics="wakunode" tid=931087 file=wakunode2.nim:164 full=/ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmMqF1RsxqHfbYsJ2Mk8UXWiVHVG9LA57beLhNWznFqhVm
DBG 2021-04-09 11:05:26.016+10:00 initWakuRelay                              topics="wakurelay" tid=931087 file=waku_relay.nim:36
DBG 2021-04-09 11:05:26.016+10:00 init                                       topics="wakurelay" tid=931087 file=waku_relay.nim:21
DBG 2021-04-09 11:05:26.016+10:00 init                                       topics="wakurelay" tid=931087 file=waku_relay.nim:21
DBG 2021-04-09 11:05:26.016+10:00 Reconnecting peers                         topics="wakupeers" tid=931087 file=peer_manager.nim:190 proto=/vac/waku/relay/2.0.0-beta2
INF 2021-04-09 11:05:26.016+10:00 mounting relay                             topics="wakunode" tid=931087 file=wakunode2.nim:403
DBG 2021-04-09 11:05:26.017+10:00 subscribe                                  topics="wakurelay" tid=931087 file=waku_relay.nim:51 pubSubTopic=/waku/2/default-waku/proto
INF 2021-04-09 11:05:26.017+10:00 subscribe                                  topics="wakunode" tid=931087 file=wakunode2.nim:185 topic=/waku/2/default-waku/proto
DBG 2021-04-09 11:05:26.017+10:00 subscribe                                  topics="wakurelay" tid=931087 file=waku_relay.nim:51 pubSubTopic=/waku/2/default-waku/proto
DBG 2021-04-09 11:05:26.017+10:00 start                                      topics="wakurelay" tid=931087 file=waku_relay.nim:77
INF 2021-04-09 11:05:26.017+10:00 relay mounted and started successfully     topics="wakunode" tid=931087 file=wakunode2.nim:432
INF 2021-04-09 11:05:26.017+10:00 Starting JSON-RPC HTTP server              topics="JSONRPC-HTTP-SERVER" tid=931087 file=httpserver.nim:211 url=http://127.0.0.1:8545
DBG 2021-04-09 11:05:26.017+10:00 Adding API topic handler for existing subscription topics="relay api" tid=931087 file=relay_api.nim:47 topic=/waku/2/default-waku/proto
INF 2021-04-09 11:05:26.017+10:00 subscribe                                  topics="wakunode" tid=931087 file=wakunode2.nim:185 topic=/waku/2/default-waku/proto
DBG 2021-04-09 11:05:26.017+10:00 subscribe                                  topics="wakurelay" tid=931087 file=waku_relay.nim:51 pubSubTopic=/waku/2/default-waku/proto
DBG 2021-04-09 11:05:26.017+10:00 MessageCache for topic                     topics="relay api" tid=931087 file=relay_api.nim:52 topic=/waku/2/default-waku/proto
DBG 2021-04-09 11:05:26.017+10:00 HTTP RPC server started                    topics="JSONRPC-HTTP-SERVER" tid=931087 file=httpserver.nim:316 address=127.0.0.1:8545
INF 2021-04-09 11:05:26.017+10:00 RPC Server started                         topics="wakunode" tid=931087 file=wakunode2.nim:527 ta=127.0.0.1:8545
```

Edit: Not blocking.

**Comment by oskarth** [comment] 2021-04-09 01:37
How is this blocking ? Just change the log target locally when building wakunode2/chat2 if you need TRACE logs, as indicated in the Makefile.

Agree dynamic logs have some issues, usually I just modify the Makefile/rebuild and it works fine, but let's not call it blocking when it isn't. It is more of a nice to have.

**Comment by D4nte** [comment] 2021-04-09 01:42
> How is this blocking ? Just change the log target locally when building wakunode2/chat2 if you need TRACE logs, as indicated in the Makefile.
> 
> Agree dynamic logs have some issues, usually I just modify the Makefile/rebuild and it works fine, but let's not call it blocking when it isn't. It is more of a nice to have.

It makes my tests fail as there are only trace logs to indicate that nim-waku received a message on relay. Another alternative would be to promote the logging of receiving a waku message via rlelay to debug.

**Comment by oskarth** [comment] 2021-04-09 03:27
Discussed in PR and Discord. Not really a blocker but would be nice for developer experience. Last time I looked into dynamic scoping of logs this is what I came across:

https://github.com/status-im/nim-waku/blob/139f1480374baadea1555624e4c2bd6efc0fde75/waku.nimble#L38-L40

```
  # XXX: When running `> NIM_PARAMS="-d:chronicles_log_level=INFO" make test2`
  # I expect compiler flag to be overridden, however it stays with whatever is
  # specified here.
```

**Comment by jm-clius** [comment] 2021-04-09 09:23
Agree that this will be useful. Unassigning myself as I'm not likely to look at it as a priority.

@D4nte I suggest that you rather add "general" issues (i.e. things that don't require immediate attention) to the [Vac PM Board](https://github.com/orgs/vacp2p/projects/3) from where they can be discussed and prioritised during PMs.

**Comment by D4nte** [comment] 2021-04-13 12:52
> Agree that this will be useful. Unassigning myself as I'm not likely to look at this as a priority.
> 
> @D4nte I suggest that you rather add "general" issues (i.e. things that don't require immediate attention) to the [Vac PM Board](https://github.com/orgs/vacp2p/projects/3) from where they can be discussed and prioritised during PMs.

Does not seem possible. I cannot add it from here and when trying to find it from the board with search `repo:status-im/nim-waku author:d4nte` it only shows issues from the rfc repo.

**Comment by jm-clius** [comment] 2021-04-13 13:02
> Does not seem possible. I cannot add it from here and when trying to find it from the board with search `repo:status-im/nim-waku author:d4nte` it only shows issues from the rfc repo.

Yeah, the board does not integrate well across repos, but you can copy and paste the (full) URL to your issue under `New`. This should at least make the issue and its current status visible.

**Comment by D4nte** [comment] 2021-04-14 02:08
> Yeah, the board does not integrate well across repos, but you can copy and paste the (full) URL to your issue under `New`. This should at least make the issue and its current status visible.

Done, thanks for the tip. It seems to be because nim-waku is not a repo linked to the Vac PM board, can we link it?

**Comment by oskarth** [comment] 2021-04-14 04:48
Different GH orgs, IIRC not supported by GH. Copy paste might be a bit ugly but it works well enough

**Comment by alrevuelta** [comment] 2022-11-02 07:35
Closing this since its a duplicate of #1197 and it was already fixed in https://github.com/status-im/nwaku/pull/1272

**Closed by alrevuelta** 2022-11-02 07:35 UTC
Labels: enhancement
