### ISSUE TITLE
WakuMessage timestamp is not set

### ISSUE THREAD

**Issue by D4nte** [status-im/nwaku#582] opened 2021-05-28 12:19 UTC
# Problem

WakuMessage has a `timestamp` field. This field is not set by the `chat2` app for outgoing messages.

Note: this field is an input parameter on the JSON RPC interface of wakunode2

# Notes

@jm-clius proposed that filling the timestamp is likely to be a waku node concern (and not application level), ie, the waku library should set the timestamp when sending a message, not the chat2 app.

If that's the direction that is taken, then I would also suggest to review the fact that the `timestamp` is an optional parameter on the JSON RPC interface of wakunode2. If it should not be an application concern then shouldn't wakunode2 the one to set the timestamp for outgoing messages?

**Comment by oskarth** [comment] 2021-07-14 09:03
fyi @staheri14 re store node moving to sender by default

**Comment by staheri14** [comment] 2021-07-16 03:35
@oskarth 
Currently, the waku store defaults to sender time
Are you suggesting removing the receiver timestamp from the waku messages?

**Comment by oskarth** [comment] 2021-07-16 05:00
The issue is about (sender) timestamp not being set in WakuMessage by default. It probably should be, given that store protocol is relying on it.

**Comment by jm-clius** [comment] 2022-06-22 14:06
Closing, as `chat2` now sets the timestamp.

**Closed by jm-clius** 2022-06-22 14:06 UTC
